services:
    _defaults:
        autowire: true
        autoconfigure: true

    VenneMedia\ContaoKiAssistent\:
        resource: '../src/'
        exclude: '../src/{ContaoManager,DependencyInjection}'
